# Text Classification:

## Data
<pre>
1. we have total of 20 types of documents(Text files) and total 18828 documents(text files).
2. You can download data from this <a href='https://drive.google.com/open?id=1rxD15nyeIPIAZ-J2VYPrDRZI66-TBWvM'>link</a>, in that you will get documents.rar folder. <br>If you unzip that, you will get total of 18828 documnets. document name is defined as'ClassLabel_DocumentNumberInThatLabel'. 
so from document name, you can extract the label for that document.
4. Now our problem is to classify all the documents into any one of the class.
5. Below we provided count plot of all the labels in our data. 
</pre>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os

source = 'documents' 
lst = []
if os.path.isdir(source):
    data_files = os.listdir(source)
    for file in data_files:
        sep = '_'
        stripped = file.split(sep, 1)[0]
        lst.append(stripped) 

In [3]:
!pip install pickle5

     |████████████████████████████████| 256 kB 7.5 MB/s 


In [4]:
import pickle5 as pickle
path_to_protocol5 = '/content/drive/MyDrive/CNN/preprocessed_data.pkl'
with open(path_to_protocol5, "rb") as fh:
  data = pickle.load(fh)

In [5]:
data.head()

text  ...                                  preprocessed_text
0  From: mathew <mathew@mantis.co.uk>\nSubject: A...  ...  alt atheism atheist resources archive atheism ...
1  From: mathew <mathew@mantis.co.uk>\nSubject: A...  ...  alt atheism introduction atheism archive athei...
2  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...  ...  gospeldating article charleywingate well john ...
3  From: mathew <mathew@mantis.co.uk>\nSubject: R...  ...  university violating separation church state u...
4  From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...  ...  soc motss princeton axes matching funds for bo...

[5 rows x 5 columns]

In [6]:
columns = ['email', 'subject', 'preprocessed_text']
data['total_data'] = data[columns].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)

data.head()

text  ...                                         total_data
0  From: mathew <mathew@mantis.co.uk>\nSubject: A...  ...   mantis netcom  atheist resources alt atheism ...
1  From: mathew <mathew@mantis.co.uk>\nSubject: A...  ...   mantis  introduction to atheism alt atheism i...
2  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...  ...   mimsy tu-bs umd dbstu1 edu  gospel dating gos...
3  From: mathew <mathew@mantis.co.uk>\nSubject: R...  ...   mantis unh kepler edu  university violating s...
4  From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...  ...   ccr-p ida Watson Com harder org watson ibm Ib...

[5 rows x 6 columns]

## Assignment:

In [7]:
data.columns

Index(['text', 'class', 'email', 'subject', 'preprocessed_text', 'total_data'], dtype='object')

In [8]:
data.iloc[400]

text                 From: perry@dsinc.com (Jim Perry)\nSubject: Re...
class                                                      alt.atheism
email                         dsinc uoknor okcforum osrhe darkside edu
subject                                                 biblical rape 
preprocessed_text    was biblicalrape this response originally fell...
total_data            dsinc uoknor okcforum osrhe darkside edu  bib...
Name: 400, dtype: object

### Training The models to Classify: 

<pre>
1. Combine "preprocessed_text", "preprocessed_subject", "preprocessed_emails" into one column. use that column to model. 

2. Now Split the data into Train and test. use 25% for test also do a stratify split. 

3. Analyze your text data and pad the sequnce if required. 
Sequnce length is not restricted, you can use anything of your choice. 
you need to give the reasoning

4. Do Tokenizer i.e convert text into numbers. please be careful while doing it. 
if you are using tf.keras "Tokenizer" API, it removes the <b>"_"</b>, but we need that.

5. code the model's ( Model-1, Model-2 ) as discussed below 
and try to optimize that models.  

6. For every model use predefined Glove vectors. 
<b>Don't train any word vectors while Training the model.</b>

7. Use "categorical_crossentropy" as Loss. 

8. Use <b>Accuracy and Micro Avgeraged F1 score</b> as your as Key metrics to evaluate your model. 

9.  Use Tensorboard to plot the loss and Metrics based on the epoches.

10. Please save your best model weights in to <b>'best_model_L.h5' ( L = 1 or 2 )</b>. 

11. You are free to choose any Activation function, learning rate, optimizer.
But have to use the same architecture which we are giving below.

12. You can add some layer to our architecture but you <b>deletion</b> of layer is not acceptable.

13. Try to use <b>Early Stopping</b> technique or any of the callback techniques that you did in the previous assignments.

14. For Every model save your model to image ( Plot the model) with shapes 
and inlcude those images in the notebook markdown cell, 
upload those imgages to Classroom. You can use "plot_model" 
please refer <a href='https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model'>this</a> if you don't know how to plot the model with shapes. 

</pre>

In [10]:
#1. Combine "preprocessed_text", "preprocessed_subject", "preprocessed_emails" into one column. use that column to model. 
my_model1_data = data[['class','total_data']]
my_model1_data.head()

class                                         total_data
0  alt.atheism   mantis netcom  atheist resources alt atheism ...
1  alt.atheism   mantis  introduction to atheism alt atheism i...
2  alt.atheism   mimsy tu-bs umd dbstu1 edu  gospel dating gos...
3  alt.atheism   mantis unh kepler edu  university violating s...
4  alt.atheism   ccr-p ida Watson Com harder org watson ibm Ib...

In [11]:
x = my_model1_data['total_data']
y = my_model1_data['class']

y.tail()

18823    talk.religion.misc
18824    talk.religion.misc
18825    talk.religion.misc
18826    talk.religion.misc
18827    talk.religion.misc
Name: class, dtype: object

In [12]:
#Encoding class label
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

encoder = LabelEncoder()
encoder.fit(y)
y_encode = encoder.transform(y)

## converting label into matrix
y_encoded = to_categorical(y_encode)

In [13]:
y_encoded[1].shape

(20,)

In [14]:
y = y_encoded

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,stratify=y)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(14121,)
(4707,)
(14121, 20)
(4707, 20)


In [16]:
import numpy as np

#Applying Padding
length_of_sentences = [len(s) for s in x_train]
length_of_sentences.sort()
length_of_sentences = np.array(length_of_sentences)

### Here we will be taking a maximum sequence length we will be taking it as 99th percent of the all the length of all sentences

In [19]:
maxlen = int(np.percentile(length_of_sentences,99))
maxlen 

9468

In [20]:
import tensorflow as tf

tokenizer = tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True, split=' '
)
tokenizer.fit_on_texts(x_train)
x_train_tok  = tokenizer.texts_to_sequences(x_train)
x_test_tok = tokenizer.texts_to_sequences(x_test)

In [21]:
import pandas as pd

pd.set_option('display.max_colwidth', None)
print(x_test.head(1))
print(x_test_tok[0])

17596     romulus rutgers freddy COM CNA TEK master remus edu  is la burning yet  burning yet article hear the jury reached verdict where did you hear this seem have missed burning yet will burn regardless the verdict not near radio count your blessings the views expressed herein are theodore kaldis own only you seriously believe that major university rutgers remus rutgers edu kaldis this would hold such views
Name: total_data, dtype: object
[7528, 853, 17416, 205, 19130, 1972, 1446, 8186, 19, 465, 33269, 1965, 242, 1965, 242, 27, 616, 1, 4403, 2287, 5344, 85, 84, 5, 616, 7, 309, 9, 1746, 1965, 242, 20, 2324, 2078, 1, 5344, 6, 712, 707, 1386, 24, 13024, 1, 1026, 1491, 6648, 8, 5613, 5537, 135, 43, 5, 1193, 105, 3, 474, 279, 853, 8186, 853, 19, 5537, 7, 18, 695, 83, 1026]


In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

x_train = pad_sequences(x_train_tok,maxlen=maxlen,padding="post")
x_test= pad_sequences(x_test_tok,maxlen=maxlen,padding='post')

print(x_train.shape)
print(x_test.shape)

(14121, 9468)
(4707, 9468)


In [23]:
embedding_dict = {}

with open('/content/drive/MyDrive/NaiveBayesAssignment/glove_vectors', 'rb') as f:
    model = pickle.load(f)
    glove_words =  set(model.keys())
    for word in glove_words:
        embedding_dict[word] = model[word]
    f.close()

In [24]:
len(tokenizer.index_word)

113515

In [25]:
## Converting embedding word to embedding matrix 

import numpy as np 

size = len(tokenizer.word_index)+1

emb_matrix = np.zeros((size,50))

for word,i in tokenizer.word_index.items():
    emb_word = embedding_dict.get(word)

    if emb_word is not None:
      emb_matrix[i]=emb_word[0:50]

In [26]:
print(emb_matrix.shape)
print(size)

(113516, 50)
113516


### Model-1: Using 1D convolutions with word embeddings

<pre>
<b>Encoding of the Text </b> --> For a given text data create a Matrix with Embedding layer as shown Below. 
In the example we have considered d = 5, but in this assignment we will get d = dimension of Word vectors we are using.
 i.e if we have maximum of 350 words in a sentence and embedding of 300 dim word vector, 
 we result in 350*300 dimensional matrix for each sentance as output after embedding layer
<img src='https://i.imgur.com/kiVQuk1.png'>
Ref: https://i.imgur.com/kiVQuk1.png

<b>Reference:</b>
<a href='https://stackoverflow.com/a/43399308/4084039'>https://stackoverflow.com/a/43399308/4084039</a>
<a href='https://missinglink.ai/guides/keras/keras-conv1d-working-1d-convolutional-neural-networks-keras/'>https://missinglink.ai/guides/keras/keras-conv1d-working-1d-convolutional-neural-networks-keras/</a>

<b><a href='https://stats.stackexchange.com/questions/270546/how-does-keras-embedding-layer-work'>How EMBEDDING LAYER WORKS </a></b>

</pre>

### Go through this blog, if you have any doubt on using predefined Embedding values in Embedding layer - https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

<img src='https://i.imgur.com/fv1GvFJ.png'>
ref: 'https://i.imgur.com/fv1GvFJ.png'

<pre>
1. all are Conv1D layers with any number of filter and filter sizes, there is no restriction on this.

2. use concatenate layer is to concatenate all the filters/channels. 

3. You can use any pool size and stride for maxpooling layer.

4. Don't use more than 16 filters in one Conv layer becuase it will increase the no of params. 
( Only recommendation if you have less computing power )

5. You can use any number of layers after the Flatten Layer.
</pre>

In [27]:
pip install -U tensorflow-estimator

In [28]:
print(len(tokenizer.word_index))
print(maxlen)

113515
9468


In [29]:
## Embedding layer 
from keras.layers import Embedding

embedding_layer = Embedding(len(tokenizer.word_index)+1, 50, embeddings_initializer=tf.keras.initializers.Constant(emb_matrix),trainable=False)

In [30]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model 
from tensorflow.keras.layers import Input,Dense,Conv1D,Flatten,Embedding,MaxPool1D,concatenate,Dropout
from tensorflow.keras.callbacks import ModelCheckpoint,TensorBoard,EarlyStopping
from tensorflow.keras.optimizers import Adam


input_layer = Input(shape=(maxlen))

embed = embedding_layer(input_layer)

#tf.keras.layers.Conv1D(
#    filters =	Integer, the dimensionality of the output space (i.e. the number of output filters in the convolution
#    kernel_size = An integer or tuple/list of a single integer, specifying the length of the 1D convolution window. 
#    activation=relu,
#    kernel_initializer=he_normal,
#    kernel_regularizer='tf.keras.regularizers.l2'
#)

Conv1D_m = Conv1D(25,4,activation="relu",kernel_initializer =tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(embed)
Conv1D_n = Conv1D(30,4,activation="relu",kernel_initializer =tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(embed)
Conv1D_o = Conv1D(35,4,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(embed)

second_layer = concatenate([Conv1D_m,Conv1D_n,Conv1D_o])

max_pool_1 = MaxPool1D(3)(second_layer)

Conv1D_i = Conv1D(25,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(max_pool_1)
Conv1D_j = Conv1D(30,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(max_pool_1)
Conv1D_k =  Conv1D(35,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(),kernel_regularizer=tf.keras.regularizers.l2())(max_pool_1)

third_layer = concatenate([Conv1D_i,Conv1D_j,Conv1D_k])

max_pool_2 = MaxPool1D(3)(third_layer)

fourth_layer = Conv1D(30,3,activation='relu',kernel_initializer = tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l2())(max_pool_2)

flatten = Flatten()(fourth_layer)

dropout_layer = Dropout(0.2)(flatten)

dense_layer = Dense(64,activation="relu",kernel_initializer = tf.keras.initializers.he_normal())(dropout_layer)
              
output_layer = Dense(20,activation="softmax",kernel_initializer= tf.keras.initializers.glorot_normal())(dense_layer)
              

model =Model(inputs=input_layer,outputs=output_layer) 
             
        

In [31]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 9468)]       0           []                               
                                                                                                  
 embedding (Embedding)          (None, 9468, 50)     5675800     ['input_1[0][0]']                
                                                                                                  
 conv1d (Conv1D)                (None, 9465, 25)     5025        ['embedding[0][0]']              
                                                                                                  
 conv1d_1 (Conv1D)              (None, 9465, 30)     6030        ['embedding[0][0]']              
                                                                                              

In [32]:
!pip install tensorflow-addons==0.8.3
!pip install tensorflow==2.2.0-rc3

     |████████████████████████████████| 1.0 MB 8.8 MB/s 
     |████████████████████████████████| 516.2 MB 10 kB/s 
     |████████████████████████████████| 2.9 MB 41.5 MB/s 
     |████████████████████████████████| 454 kB 55.1 MB/s 
     |████████████████████████████████| 3.0 MB 48.0 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5.3
  Attempting uninstall: tensorflow
    Foun

In [33]:
import tensorflow_addons as tfa
from tensorflow_addons.metrics import F1Score

In [34]:
checkpoint = ModelCheckpoint(filepath='best_model_1.h5',verbose=1,monitor='val_accuracy',mode='max',save_best_only=True)
 
early_stop = EarlyStopping(monitor="val_accuracy",mode='max',patience=2)

log_dir = "logs"
tensorboard = TensorBoard(log_dir=log_dir,histogram_freq=1,write_graph=True)

callbacks =[checkpoint,early_stop,tensorboard]

model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy',F1Score(average='micro',num_classes=20)])

model.fit(x_train,y_train,epochs=15,verbose=2,validation_data=(x_test,y_test),batch_size =64,callbacks=callbacks) 

Epoch 1/15


/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:2034: UserWarning: Metric F1Score implements a `reset_states()` method; rename it to `reset_state()` (without the final "s"). The name `reset_states()` has been deprecated to improve API consistency.
  m.reset_state()



Epoch 1: val_accuracy improved from -inf to 0.14170, saving model to best_model_1.h5
221/221 - 935s - loss: 2.9940 - accuracy: 0.0957 - f1_score: 0.0957 - val_loss: 2.5068 - val_accuracy: 0.1417 - val_f1_score: 0.1417 - 935s/epoch - 4s/step
Epoch 2/15

Epoch 2: val_accuracy improved from 0.14170 to 0.18334, saving model to best_model_1.h5
221/221 - 845s - loss: 2.4849 - accuracy: 0.1513 - f1_score: 0.1513 - val_loss: 2.3422 - val_accuracy: 0.1833 - val_f1_score: 0.1833 - 845s/epoch - 4s/step
Epoch 3/15

Epoch 3: val_accuracy improved from 0.18334 to 0.21372, saving model to best_model_1.h5
221/221 - 853s - loss: 2.3646 - accuracy: 0.1924 - f1_score: 0.1924 - val_loss: 2.2493 - val_accuracy: 0.2137 - val_f1_score: 0.2137 - 853s/epoch - 4s/step
Epoch 4/15

Epoch 4: val_accuracy improved from 0.21372 to 0.23284, saving model to best_model_1.h5
221/221 - 837s - loss: 2.3203 - accuracy: 0.2098 - f1_score: 0.2098 - val_loss: 2.2409 - val_accuracy: 0.2328 - val_f1_score: 0.2328 - 837s/epoch 

### Model-2 : Using 1D convolutions with character embedding

<pre>
<pre><img src="https://i.ytimg.com/vi/CNY8VjJt-iQ/maxresdefault.jpg" width="70%">
Here are the some papers based on Char-CNN
 1. Xiang Zhang, Junbo Zhao, Yann LeCun. <a href="http://arxiv.org/abs/1509.01626">Character-level Convolutional Networks for Text Classification</a>.NIPS 2015
 2. Yoon Kim, Yacine Jernite, David Sontag, Alexander M. Rush. <a href="https://arxiv.org/abs/1508.06615">Character-Aware Neural Language Models</a>. AAAI 2016
 3. Shaojie Bai, J. Zico Kolter, Vladlen Koltun. <a href="https://arxiv.org/pdf/1803.01271.pdf">An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence Modeling</a>
 4. Use the pratrained char embeddings <a href='https://github.com/minimaxir/char-embeddings/blob/master/glove.840B.300d-char.txt'>https://github.com/minimaxir/char-embeddings/blob/master/glove.840B.300d-char.txt</a>
</pre>

<img src='https://i.imgur.com/EuuoJtr.png'>

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,stratify=y)

In [36]:
tokenize_char = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',char_level= True,oov_token='UNK')
tokenize_char.fit_on_texts(x_train)

In [37]:
print(tokenize_char.word_index)

size_char = len(tokenize_char.word_index)+1
print(size_char)

{'UNK': 1, ' ': 2, 'e': 3, 't': 4, 'a': 5, 'o': 6, 'i': 7, 'n': 8, 's': 9, 'r': 10, 'h': 11, 'l': 12, 'd': 13, 'c': 14, 'u': 15, 'm': 16, 'p': 17, 'g': 18, 'y': 19, 'w': 20, 'f': 21, 'b': 22, 'v': 23, 'k': 24, 'x': 25, 'j': 26, 'z': 27, 'q': 28, '_': 29, '1': 30, '0': 31, '2': 32, '-': 33, '3': 34, '4': 35, '6': 36, '5': 37, '8': 38, '9': 39, '7': 40}
41


In [38]:
x_train[:5]

17328     cleveland Freenet Edu  synagogues mosques and double standards synagogues mosques and writes responding discussion about mosque jerusalem allegedly having been destroyed israel todayis there feature story about the ongoing restoration synagogues the jewishquarter the author leah abramowitz writes that there were fifty seven synagogues the quarter all which were destroyed some she says used donkey stables the building shells that still find really really hard understand why the demolition the buildings front the kotel continues evoke more outrage than this everything much cheaper when happens the jews why the double standard human behavior regarding the jews must manitained perfect example the outcry over the temporary removal men who advocated murdering jews and destroying the state israel compared the deafening silence over the abusive treatment jews arab countries during the past years compare the tacit appoval that the world gives muslims who randomly murder jewish civilia

In [39]:
## Tokenize them 
x_train = tokenize_char.texts_to_sequences(x_train)
x_test = tokenize_char.texts_to_sequences(x_test)

In [40]:
#Applying Padding
length_of_sentences = [len(s) for s in x_train]
length_of_sentences.sort()
length_of_sentences = np.array(length_of_sentences)

In [41]:
maxlen = int(np.percentile(length_of_sentences,99))
print(maxlen)

9123


In [42]:
x_train = pad_sequences(x_train,maxlen=maxlen,padding="post")
x_test = pad_sequences(x_test,maxlen=maxlen,padding="post")
print(f"x_train_shape{x_train.shape}")
print(f"x_train_shape{x_test.shape}")

x_train_shape(14121, 9123)
x_train_shape(4707, 9123)


In [43]:
emb_matrix_char = np.zeros((41,41))

#print(tokenize_char.word_index)
for i,j in tokenize_char.word_index.items():
  emb_matrix_char[j][j]=1

In [44]:
print(emb_matrix_char)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [45]:
embedding_layer_char = Embedding(len(tokenize_char.word_index)+1,41, embeddings_initializer=tf.keras.initializers.Constant(emb_matrix_char),input_length=maxlen,trainable=False)

In [46]:
first_layer = Input(shape=(maxlen))

embed = embedding_layer_char(first_layer)

In [47]:
m1 = Conv1D(64,3,activation="relu",kernel_initializer =tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l1())(embed)

n1 = Conv1D(64,3,activation="relu",kernel_initializer =tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l1())(m1)


max_pool_1 = MaxPool1D(5)(n1)

o1 = Conv1D(64,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l1())(max_pool_1)

i1 = Conv1D(64,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l1())(o1)


max_pool_2 = MaxPool1D(5)(i1)

i1 = Conv1D(64,3,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(seed=42),kernel_regularizer=tf.keras.regularizers.l1())(max_pool_2)


max_pool_3 = MaxPool1D(5)(i1)

flatten = Flatten()(max_pool_3)

dropout_layer = Dropout(0.5)(flatten)

dense_layer1 = Dense(256,activation="relu",kernel_initializer = tf.keras.initializers.he_normal(seed=42))(dropout_layer)


              
output_layer = Dense(20,activation="softmax",kernel_initializer= tf.keras.initializers.glorot_normal(seed=42))(dense_layer1)
              

model =Model(inputs=first_layer,outputs=output_layer)

In [48]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 9123)]            0         
                                                                 
 embedding_1 (Embedding)     (None, 9123, 41)          1681      
                                                                 
 conv1d_7 (Conv1D)           (None, 9121, 64)          7936      
                                                                 
 conv1d_8 (Conv1D)           (None, 9119, 64)          12352     
                                                                 
 max_pooling1d_2 (MaxPooling  (None, 1823, 64)         0         
 1D)                                                             
                                                                 
 conv1d_9 (Conv1D)           (None, 1821, 64)          12352     
                                                           

In [49]:
checkpoint = ModelCheckpoint(filepath='best_model_1.h5',verbose=1,monitor='val_accuracy',mode='max',save_best_only=True)
 
early_stop = EarlyStopping(monitor="val_accuracy",mode='max',patience=2)

log_dir = "logs"
tensorboard = TensorBoard(log_dir=log_dir,histogram_freq=1,write_graph=True)

callbacks =[checkpoint,early_stop,tensorboard]

model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy',F1Score(average='micro',num_classes=20)])

model.fit(x_train,y_train,epochs=15,verbose=2,validation_data=(x_test,y_test),batch_size =64,callbacks=callbacks) 

Epoch 1/15


/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:2034: UserWarning: Metric F1Score implements a `reset_states()` method; rename it to `reset_state()` (without the final "s"). The name `reset_states()` has been deprecated to improve API consistency.
  m.reset_state()



Epoch 1: val_accuracy improved from -inf to 0.05205, saving model to best_model_1.h5
221/221 - 538s - loss: 17.9402 - accuracy: 0.0625 - f1_score: 0.0625 - val_loss: 3.3711 - val_accuracy: 0.0521 - val_f1_score: 0.0521 - 538s/epoch - 2s/step
Epoch 2/15

Epoch 2: val_accuracy did not improve from 0.05205
221/221 - 571s - loss: 3.0902 - accuracy: 0.0490 - f1_score: 0.0490 - val_loss: 3.0601 - val_accuracy: 0.0516 - val_f1_score: 0.0516 - 571s/epoch - 3s/step
Epoch 3/15

Epoch 3: val_accuracy improved from 0.05205 to 0.05269, saving model to best_model_1.h5
221/221 - 579s - loss: 3.0603 - accuracy: 0.0517 - f1_score: 0.0517 - val_loss: 3.0595 - val_accuracy: 0.0527 - val_f1_score: 0.0527 - 579s/epoch - 3s/step
Epoch 4/15

Epoch 4: val_accuracy did not improve from 0.05269
221/221 - 583s - loss: 3.0603 - accuracy: 0.0514 - f1_score: 0.0514 - val_loss: 3.0594 - val_accuracy: 0.0527 - val_f1_score: 0.0527 - 583s/epoch - 3s/step
Epoch 5/15

Epoch 5: val_accuracy did not improve from 0.05269
